# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf241d78db5ac62be447b5ecfe0fd630f87766e38c9e0fb97a0c208b0aeeb92324779cbe2e974d639617994b7c7dff69e64a40396418401853133fc3fcc8ebef

test:
  secret_key_base: 770252630bbd80246908c32f4e07b4c139e3eead7ed8281a6a8dd644b4b4444445e2fa67f778757254d975930578599925cdafd55903f88de60e8b56f613a0f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
